/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
var city = "台北市";
var cities = ["台北市","新北市","台中市","台南市","高雄市","基隆市","桃園市","新竹市","新竹縣","苗栗縣","彰化縣","南投縣","雲林縣","嘉義市","嘉義縣","屏東縣","宜蘭縣","花蓮縣","台東縣","澎湖縣","金門縣","連江縣"]
var celsius = function(temp){
  return Math.round((temp-32)/(9/5));
}
var forecast = new Array();
var days = ["day1","day2","day3"]
  // you can add a icon to a html canvas. simply supply its element id and the weather you want to show.
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start all icons animation!
  skycons.play();

  // update a icon on  canvas by its id
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);

/*
Get value from Bootstrap dropdown menu
*/
var getWeather = function(city){
  var apiUrl = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22"+city+"%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys"
  var temp;
  $.getJSON(apiUrl,function(data){
    temp = data.query.results.channel.item.condition.temp;
    $(".temperature").text(celsius(temp));
    today_forecast = data.query.results.channel.item.condition.code;
    skycons.set("today", Icon(parseInt(today_forecast)));
    var date = data.query.results.channel.item.condition.date;
    $(".date").text(date.slice(4,date.length - 13))
    for(var i=0;i<3;i++){
      forecast[i] = new Array;
      forecast[i][0] = data.query.results.channel.item.forecast[i + 1].code;
      forecast[i][1] = celsius(data.query.results.channel.item.forecast[i + 1].high);
      forecast[i][2] = celsius(data.query.results.channel.item.forecast[i + 1].low);
      forecast[i][3] = data.query.results.channel.item.forecast[i + 1].date;
      $('#'+days[i]+'-date').text(forecast[i][3]);
      $('#'+days[i]+'-temp').text(forecast[i][2]+ "℃ ~ "+forecast[i][1]+"℃");
    }
  })
}
$(document).ready(function(){
  getWeather(city);
  function t(src){
    $.getJSON(src,function(data){
      var temp = celsius(data.query.results.channel.item.condition.temp);
      return temp;
    })
  }
  $.each(cities,function(i,val){
    src = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22" + val + "%20City%2C%20ak%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys"
    $(".dropdown-menu").append("<li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\"><p id = 'temp" + i + "'>" + val + " " + "</p></a></li>")
    $.getJSON(src,function(data){
      $('#temp'+i).append(celsius(data.query.results.channel.item.condition.temp))
    })
  });
  $('#dropdown li').on('click', function(){
    city = $(this).text();
    $('.dropdown-toggle').html(city);
    getWeather(city);
  });
})
var Icon = function(code) {
  if ((code > 0 && code < 5) || (code == 35) || (code >= 37 && code < 41) || (code == 45 || code == 47)) {
    return Skycons.RAIN;
  } else if ((code > 4 && code <= 11) || (code == 18) || code == 12) {
    return Skycons.SLEET
  } else if ((code > 30 && code < 33) || (code == 36)) {
    return Skycons.CLEAR_DAY
  } else if (code == 34) {
    return Skycons.CLEAR_NIGHT
  } else if (code == 30 || code == 28 || code == 26 || code == 44) {
    return Skycons.PARTLY_CLOUDY_DAY
  } else if (code == 27 || code == 29) {
    return Skycons.PARTLY_CLOUDY_NIGHT
  } else if ((code > 12 && code < 18) || (code >= 41 && code < 44) || (code == 46)) {
    return Skycons.SNOW
  } else if (code > 19 && code < 23) {
    return Skycons.FOG
  } else if (code == 24) {
    return Skycons.WIND
  }else{
    return Skycons.CLOUDY
  }
}